name: Actions required by HACS

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v2"
        - name: Validate with hassfest
          uses: "home-assistant/actions/hassfest@master"
        - name: HACS Action
          uses: "hacs/action@main"
          with:
            category: "integration"